micronaut:
  application:
    name: micronaut
  server:
    host: localhost
    port: 8080
    cors:
      enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
